# Generated by Django 5.0.2 on 2024-02-29 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('started_at', models.DateTimeField(verbose_name='Дата старта')),
                ('min_count_students', models.PositiveIntegerField(verbose_name='Минимальное количество студентов')),
                ('max_count_students', models.PositiveIntegerField(verbose_name='Максимальное количество студентов')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.author', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('link_video', models.URLField(verbose_name='Ссылка на видео')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='webapp.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.product', verbose_name='Продукт')),
            ],
        ),
    ]
